title: Contributorcoin Jekyll Theme
description: GitHub Pages Jekyll template for Contributorcoin docs.
show_downloads: true
show_gh_edit: true
show_toc: true
google_analytics:
toc_title: 

theme: contributorcoin-jekyll-theme
github:
  repository_url: https://github.com/contributorcoin/contributorcoin-jekyll-theme
  source:
    path: /
    branch: main